In [10]:
!pip install pandas
import pandas as pd

df_test = pd.read_csv("Filam_Pillar Church Directory - Main.csv")
df_test.head(10)

/Users/dvgenis/.zshenv:.:1: no such file or directory: /var/folders/jb/4gkhgpz15bbgklmqj7_zh0hm0000gn/T/cursor-sandbox-cache/048d0f1034c67a180f3455d4f39f3313/cargo/env
Requirement already satisfied: pandas in /Users/dvgenis/miniconda3/lib/python3.13/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in /Users/dvgenis/miniconda3/lib/python3.13/site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/dvgenis/miniconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/dvgenis/miniconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

,Church_Affiliation,First_Name,Last_Name,Birthday,Home_Address,Phone_Number,Email_Address,Wedding_Anniversary,Spouse_Name,Spouse_Birthday,Spouse_Phone,Children_Names,Children_Birthdays,Is_Member,Opt_In_Announcements
0,Filam,Nelson,Acain,02/05,"4146 N Meade Ave, Chicago, IL 60634",7.737589e+09,neltina1@gmail.com,03/18,Tina Acain,03/12,7.737588e+09,"Andrea, Aurea","12/06, 06/18",True,True
1,Filam,Tina,Acain,03/12,"4146 N Meade Ave, Chicago, IL 60634",7.737588e+09,neltina1@gmail.com,03/18,Nelson Acain,02/05,7.737589e+09,"Andrea, Aurea","12/06, 06/18",True,True
2,Filam,Aurea,Acain,06/18,"4146 N Meade Ave, Chicago, IL 60634",7.735582e+09,acainaurea3@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,True,True
3,Filam,Andrea,Acain,12/06,"4146 N Meade Ave, Chicago, IL 60634",7.735582e+09,andreajacain@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,True,True
4,Filam,Ruel (Pastor),Akut,07/15,"5253 W Byron St, Chicago, IL 60641",7.737045e+09,jvakut@yahoo.com,10/21,NaN,NaN,NaN,NaN,NaN,True,True
5,Filam,Jocelyn,Akut,08/25,"5253 W Byron St, Chicago, IL 60641",7.737045e+09,jvakut@yahoo.com,10/21,NaN,NaN,NaN,NaN,NaN,True,True
6,Filam,Kris Paolo (Pastor),Akut,09/21,"5253 W Byron St, Chicago, IL 60641",7.737045e+09,kpvakut21@gmail.com,10/16,NaN,NaN,NaN,NaN,NaN,True,True
7,Filam,Shekinah,Akut,11/16,"5253 W Byron St, Chicago, IL 60641",3.129754e+09,sheksinon@gmail.com,10/16,NaN,NaN,NaN,NaN,NaN,True,True
8,Pillar,Electry,Baguio,01/05,"3633 Farnsworth Dr, West Lafayette, IN 47906",7.654138e+09,electry05@yahoo.com,NaN,NaN,NaN,NaN,NaN,NaN,False,False
9,Filam,Lyonel Polde,Baguio,08/30,"183 E River Rd, Unit F6, Des Plaines, IL 60016",7.738888e+09,hary8t@gmail.com,06/29,Harriet Baguio,03/17,7.738077e+09,Casey Shane,03/06,True,True

In [11]:
required_columns = [
    "Church_Affiliation",
    "First_Name",
    "Last_Name",
    "Birthday",
    "Home_Address"
]

# Drop rows with missing/NaN/empty values in the required columns
df_filled = df_test.dropna(subset=required_columns)

# Remove trimmed empty strings too
for col in required_columns:
    df_filled = df_filled[df_filled[col].astype(str).str.strip() != '']

# Keep just "Is_Member" and "Opt_In_Announcements" in addition (no missing enforcement for these)
cols_to_show = required_columns + ["Is_Member", "Opt_In_Announcements", "Wedding_Anniversary"]
df_filled = df_filled[cols_to_show].reset_index(drop=True)
df_filled

,Church_Affiliation,First_Name,Last_Name,Birthday,Home_Address,Is_Member,Opt_In_Announcements,Wedding_Anniversary
0,Filam,Nelson,Acain,02/05,"4146 N Meade Ave, Chicago, IL 60634",True,True,03/18
1,Filam,Tina,Acain,03/12,"4146 N Meade Ave, Chicago, IL 60634",True,True,03/18
2,Filam,Aurea,Acain,06/18,"4146 N Meade Ave, Chicago, IL 60634",True,True,NaN
3,Filam,Andrea,Acain,12/06,"4146 N Meade Ave, Chicago, IL 60634",True,True,NaN
4,Filam,Ruel (Pastor),Akut,07/15,"5253 W Byron St, Chicago, IL 60641",True,True,10/21
...,...,...,...,...,...,...,...,...
166,Filam,Celina,Wonders,10/08,"327 Garrison Cir, Port Barrington, IL 60010",True,True,01/25
167,Pillar,Duke,Zambarrano,04/07,"321 Hickory Oaks Dr, Bolingbrook, IL 60490",False,False,NaN
168,Pillar,Adi,Zapanta,05/23,"321 Hickory Oaks Dr, Bolingbrook, IL 60490",False,False,NaN
169,Pillar,Adonis,Zapanta,10/15,"321 Hickory Oaks Dr, Bolingbrook, IL 60490",False,False,11/02
170,Pillar,Merlrose (Dimple),Zapanta,11/04,"321 Hickory Oaks Dr, Bolingbrook, IL 60490",False,False,11/02

In [12]:
# Summary statistics for numeric/bool columns
desc_num = df_filled.describe(include=[float, int, bool])
for col in desc_num.columns:
    print(f"For numeric/bool column '{col}':")
    for stat in desc_num.index:
        print(f"    {stat.capitalize()}: {desc_num.at[stat, col]}")
    print()

# Summary statistics for object/categorical columns
desc_obj = df_filled.describe(include=[object])
for col in desc_obj.columns:
    print(f"For column '{col}':")
    count = desc_obj.at['count', col]
    unique = desc_obj.at['unique', col]
    top = desc_obj.at['top', col]
    freq = desc_obj.at['freq', col]
    print(f"    There are {int(count)} non-missing values.")
    print(f"    There are {int(unique)} unique values.")
    print(f"    The most common value is '{top}', occurring {int(freq)} times.")
    print()

# Show number of missing values per column
missing_vals = df_filled.isnull().sum()
for col, n_missing in missing_vals.items():
    if n_missing == 0:
        print(f"There are no missing values for column '{col}'.")
    else:
        print(f"There are {n_missing} missing values for column '{col}'.")

# Show count of unique values per column
unique_counts = df_filled.nunique()
for col, n_unique in unique_counts.items():
    print(f"Column '{col}' has {n_unique} unique value(s).")

# Show top 5 most frequent values for each column
for col in df_filled.columns:
    print(f"For column '{col}', the 5 most common values and their counts are:")
    vc = df_filled[col].value_counts().head()
    for val, count in vc.items():
        print(f"    '{val}': {count} times")
    print()

For numeric/bool column 'Is_Member':
    Count: 171
    Unique: 2
    Top: False
    Freq: 91

For numeric/bool column 'Opt_In_Announcements':
    Count: 171
    Unique: 2
    Top: True
    Freq: 97

For column 'Church_Affiliation':
    There are 171 non-missing values.
    There are 2 unique values.
    The most common value is 'Pillar', occurring 94 times.

For column 'First_Name':
    There are 171 non-missing values.
    There are 168 unique values.
    The most common value is 'Joan', occurring 2 times.

For column 'Last_Name':
    There are 171 non-missing values.
    There are 65 unique values.
    The most common value is 'Basillo', occurring 7 times.

For column 'Birthday':
    There are 171 non-missing values.
    There are 142 unique values.
    The most common value is '09/06', occurring 3 times.

For column 'Home_Address':
    There are 171 non-missing values.
    There are 62 unique values.
    The most common value is '1404 Aster Ln, Bolingbrook, IL 60490', occurring 6 times.

For column 'Wedding_Anniversary':
    There are 98 non-missing values.
    There are 47 unique values.
    The most common value is '06/29', occurring 4 times.

There are no missing values for column 'Church_Affiliation'.
There are no missing values for column 'First_Name'.
There are no missing values for column 'Last_Name'.
There are no missing values for column 'Birthday'.
There are no missing values for column 'Home_Address'.
There are no missing values for column 'Is_Member'.
There are no missing values for column 'Opt_In_Announcements'.
There are 73 missing values for column 'Wedding_Anniversary'.
Column 'Church_Affiliation' has 2 unique value(s).
Column 'First_Name' has 168 unique value(s).
Column 'Last_Name' has 65 unique value(s).
Column 'Birthday' has 142 unique value(s).
Column 'Home_Address' has 62 unique value(s).
Column 'Is_Member' has 2 unique value(s).
Column 'Opt_In_Announcements' has 2 unique value(s).
Column 'Wedding_Anniversary' has 47 unique value(s).
For column 'Church_Affiliation', the 5 most common values and their counts are:
    'Pillar': 94 times
    'Filam': 77 times

For column 'First_Name', the 5 most common values and their counts are:
    'Joan': 2 times
    'Eli': 2 times
    'John': 2 times
    'Nelson': 1 times
    'Tina': 1 times

For column 'Last_Name', the 5 most common values and their counts are:
    'Basillo': 7 times
    'Benliro': 6 times
    'Briz': 6 times
    'Esteves': 5 times
    'Luardo': 5 times

For column 'Birthday', the 5 most common values and their counts are:
    '09/06': 3 times
    '01/27': 3 times
    '12/06': 2 times
    '08/25': 2 times
    '09/08': 2 times

For column 'Home_Address', the 5 most common values and their counts are:
    '1404 Aster Ln, Bolingbrook, IL 60490': 6 times
    '16542 S Sun Mdw Dr, Lockport, IL 60441': 6 times
    '2935 N Parkside Ave, Chicago, IL 60634': 5 times
    '734 N Emroy Ave, Elmhurst, IL 60126': 5 times
    '3758 N Whipple St, Chicago, IL 60618': 5 times

For column 'Is_Member', the 5 most common values and their counts are:
    'False': 91 times
    'True': 80 times

For column 'Opt_In_Announcements', the 5 most common values and their counts are:
    'True': 97 times
    'False': 74 times

For column 'Wedding_Anniversary', the 5 most common values and their counts are:
    '06/29': 4 times
    '05/17': 4 times
    '07/21': 4 times
    '01/29': 4 times
    '12/28': 3 times

/var/folders/jb/4gkhgpz15bbgklmqj7_zh0hm0000gn/T/ipykernel_52185/1044255062.py:10: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  desc_obj = df_filled.describe(include=[object])

In [13]:
df_filled.to_csv('Filled_Df/df_filled.csv', index=False)